### ISSUE TITLE
Dockerfile pulls so much more packages than what may be needed

### ISSUE THREAD

**Issue by 130s** [Field-Robotics-Lab/dockwater#32]
# Issue
1. Why installing `desktop` of ros at [`apt install ros-${ROSDIST}-desktop`](https://github.com/Field-Robotics-Lab/dockwater/blob/a2a046cb36689cd0fb24ff53d8fcb1f04d1d4f5c/humble/Dockerfile#L70)? That pulls way too many packages than what are probably needed.
   - Often when I'm in weak Internet, pulling a lot becomes an annoyance.
1. (Optional) Why installing so many packages [via `apt` directly](https://github.com/Field-Robotics-Lab/dockwater/blob/a2a046cb36689cd0fb24ff53d8fcb1f04d1d4f5c/humble/Dockerfile#L120) without using any dependency management tool e.g. `rosdep install`? I'm just curious though, defining deps in `Dockerfile` directly as a list of arguments to `apt install` looks nothing better than quick and dirty (maybe that's what this repo started from?) and could raise maintenance effort much higher unnecessarily.

**Comment by M1chaelM** [comment]
Hi @130s yes, the images in this use `apt` to manage dependencies rather than `rosdep`. Also, yes, the images were designed primarily for classroom use and experimentation and are not optimized for low-bandwidth connections or long-term maintenance. 

I'm going to close this issue since it does not report a bug or request a feature. However, assuming this is a feature request in disguise, it should be fairly straightforward for you to modify the image in the way that you are requesting, and you are of course welcome to do this. If you'd like to contribute it back to this repository, just create a pull request and include a short writeup of the additional features you are adding. If your image supports our primary use cases we will consider merging it.

**Comment by 130s** [comment]
Sounds fair to close, as I didn't make what I wanted clear.

I want to ask a bit further. I came to this repo from [vrx/docker_install_tutorial](https://github.com/osrf/vrx/wiki/docker_install_tutorial). I know VRX is a competition among, students-only? But that whole simulation toolset itself seems legit and valuable (don't get me wrong, I'm just trying to say it looks way more than classroom or quick experiment projects). Because it's a dependency of such projects, maybe worth polishing up?
